### PR TITLE
Refactor to a new cached Dockerfile

### PR DESCRIPTION
**Pull request by containscafeine**

### CODE REVIEW

**Comment by kflynn** [comment]
There's a conflict here, but also, `$(AMBASSADOR_DOCKER_IMAGE)-cached` will change for nearly every build, which negates the benefit of the cached base image. Let's separate the names, and assume that we'll manually update the cached base when need be.

**Comment by kflynn** [comment]
Moving back to "In Progress" since this needs more work.

**Comment by containscafeine** [comment]
@kflynn I've made the changes, PTAL! :)

**Comment by containscafeine** [comment]
@kflynn to test this out, you'll first need to run `make ambassador-docker-image-cached` and then build the image.
This now builds 2 cached container images; one for caching install time dependencies and another for runtime dependencies (curl, python3, ambex, kubewatch).

Once both are built and pushed, we can go ahead with this.

Curious though about how do you feel about 2 cached images :confused:

**Comment by kflynn** [comment]
It took a little reading to figure out the point of the two, but I think I have a clue now. Cool.

**Comment by kflynn** [comment]
Oops. I made a conflict for you when I took your validation fix, mea culpa! If you can fix that I think we're good to go here!

**Pull request merged**
