### PR TITLE
kat: tracing test for HTTP auth service

### PR DESCRIPTION
**Pull request by gsagula**
## Description
This PR adds a test for verifying that an external authorization server receives the proper tracing
headers when Ambassador is configured with an HTTP AuthService.

### CODE REVIEW

**Comment by gsagula** [comment]
Test failures seem to be unrelated to the changes.

**Comment by kflynn** [comment]
Hmmmm, I'm a little more concerned -- we don't typically see `TracingTest` flakes. It works for you locally?

**Comment by gsagula** [comment]
It passes locally, but I can take another look at.

**Comment by gsagula** [comment]
What is failing locally for me now is this assert:
```
assert self.results[100].backend.response[0] == 'tracingtest-default'
```

**Comment by gsagula** [comment]
@kflynn Tests are fixed. PTAL, thank you!

**Pull request merged**
