### PR TITLE
Adding documentation for cluster timeouts

### PR DESCRIPTION
**Pull request by peturgq**
## Description
Documentation for the cluster timeout feature.

### CODE REVIEW

**Comment by richarddli** [comment]
Thanks! The term `cluster` isn't something we generally expose to Ambassador users; I'm thinking that it makes sense to create a `timeout.md` document (like we do for `rewrite`, `cors`, etc.) that talks about this in more detail. Is this something you could do?

**Comment by peturgq** [comment]
I'll maybe take a look at it this evening/tomorrow.

**Comment by richarddli** [comment]
Yes, OK, we need to do this especially now with #1426 too

**Comment by peturgq** [comment]
Timeout PR:
https://github.com/emissary-ingress/emissary/pull/1393

**Pull request merged**
