### PR TITLE
Change objects_to_process tuple to use full filepath

### PR DESCRIPTION
**Pull request by lavoiedn**
My attempt at a fix for #494

### CODE REVIEW

**Comment by lavoiedn** [comment]
I just realised this PR could perhaps use a renaming from `filename` to `filepath` in the `process_all_objects` function? Let me know if this fix seems sound and if you'd prefer the variable be renamed.

**Comment by kflynn** [comment]
Yeah, I think I agree that `filename` needs to become `filepath` in `Config.load_yaml` and `Config.process_all_objects`... which leads us to the ugliness of whether to rename `self.filename`. Sadly, I think it's probably less ugly to do that now rather than waiting. 😦

**Comment by lavoiedn** [comment]
I changed some more instances of `filename` but then I realized it's used in the `source` object which would require changing a lot of test json files.

I'll get a test environment setup tomorrow so I can run python tests and try it out in minikube!

**Comment by lavoiedn** [comment]
@kflynn I wrote another possible fix that involves less drastic changes for the code base and the unit tests seem to work with it: https://github.com/datawire/ambassador/compare/master...lavoiedn:fix-process_all_objects-same-filename-redux?expand=1&w=1

If you'd rather I change the "`filename`" key/value in every instance of the `source` dict, I can do that too! I just don't want to break a portion of the code that uses "`filename`". I didn't seem to find any instance in the code that required `source.filename` to be unique across multiple sources, except maybe in the diagnostic html?

```bash
$ grep -r -e "{{ source.filename }}"          
ambassador/templates/diag.html:              <a href="/ambassador/v0/diag/{{ source.filename }}">
ambassador/templates/diag.html:                <a href="/ambassador/v0/diag/{{ source.filename }}">
```

Let me know which solution you prefer! I think using `filepath` everywhere would be cleaner and more of a long-term fix, but I'm not sure of the implications.

**Comment by lavoiedn** [comment]
Okay just confirmed that the second fix does not work with the diagnostics dashboard. We're out on a team building event this afternoon but I'll be able to invest more time into this tomorrow!

**Pull request closed without merging**
