### PR TITLE
docs: Telepresence: Update for 2.0.1

### PR DESCRIPTION
**Pull request by LukeShu**
What it says in the title.

### CODE REVIEW

**Review by mattmcclure-dw — COMMENTED** [review]
lgtm

**Review by mattmcclure-dw — CHANGES_REQUESTED** [review]
line 43, environt -> enviroment?

**Comment by LukeShu** [comment]
> line 43, environt -> enviroment?

Oops, fixed! (And also "seprate")

**Review by mattmcclure-dw — APPROVED** [review]
lgtm, for real this time

**Pull request merged**
