### PR TITLE
add sni support for tls origination

### PR DESCRIPTION
**Pull request by jwm**
## Description
Adds a configurable SNI hostname on originated TLS connections.

## Related Issues
#2043

## Testing
We ran this in production for a few weeks, but with Ambassador 0.75. I ported it to the current `master`, but gave up on writing tests after spending an hour or two trying to get the test suite to work, even after feeding it a fresh, dedicated EKS cluster (most of the pods were failing because they couldn't execute `entrypoint.sh`.

## Todos
- [ ] Tests
- [X] Documentation

### CODE REVIEW

**Comment by CamelCaseNotation** [comment]
@jwm is this needed because the upstream service is a server which does different things depending on the SNI?

**Comment by jwm** [comment]
@CamelCaseNotation yup, exactly.

**Comment by kflynn** [comment]
Hey @jwm, this code looks sane -- my apologies for letting this linger, Edge Stack 1.0 has had us pretty backed up for awhile. Can you resolve the conflicts and let me sort out when we can get this in?

Thanks! 🙂

**Comment by jwm** [comment]
@kflynn No worries, I just rebased onto the current `master` -- take a look now?

**Comment by kflynn** [comment]
Many thanks! I'm going to look at a test for this, since I need to see if the KAT backend can detect SNI at all. 😐  Could you also add it to the `v2` `TLSContext` schema? 🙂  (I assume you're running with it in the `v1` context, right?)

**Comment by jwm** [comment]
Sure, done. And yup, we're running with the `v1` context.

**Pull request merged**
