### PR TITLE
builder.sh: Only embed the apro.git version number in Go binaries

### PR DESCRIPTION
**Pull request by LukeShu**
Per our discussion.

### CODE REVIEW

**Comment by ark3** [comment]
Okay, so this will use apro.version for all go binaries, if it exists, or otherwise leave binaries as (no version). Is that right?

**Comment by LukeShu** [comment]
> Okay, so this will use apro.version for all go binaries, if it exists, or otherwise leave binaries as (no version). Is that right?

That's correct.

**Comment by ark3** [comment]
Okay, so OSS builds will be versionless. I guess that's fine. I think we should remove Edge Control build/push/tag/promote from OSS CI, then.

**Comment by kflynn** [comment]
Concur re not building `edgectl` from A/OSS CI.

**Comment by LukeShu** [comment]
I'm about to add another commit.

**Comment by ark3** [comment]
This loses basically all the module-generic aspects of the new build system.

**Comment by LukeShu** [comment]
> This loses basically all the module-generic aspects of the new build system.

kiiiiinda? There always has and continues to be a bit that is specific to the python ambassador.

**Comment by LukeShu** [comment]
I think what's left is to revert b42e55c and d655c26 and to re-create them in apro.git?

**Comment by ark3** [comment]
Yes, that sounds right. How shall we proceed?

**Comment by LukeShu** [comment]
Oh, also, `VERSION.py` needs hacked up to parse `apro.version` instead of (in addition to?) `ambassador.version`.

**Comment by LukeShu** [comment]
```console
$ find / -name '*.version'
/usr/lib/python3.7/site-packages/ambassador-0.0.0.dev0-py3.7.egg/ambassador.version
/buildroot/ambassador/python/ambassador.version
/buildroot/ambassador/python/apro.version
```
Unfortunately, it seems that `/usr/lib/python3.7/site-packages/ambassador-0.0.0.dev0-py3.7.egg/ambassador.version` is the file that it's reading, so with the `builder.sh` on this branch, it isn't as simple as `s/ambassador/apro/` in the filename in `VERSION.py`

**Comment by LukeShu** [comment]
Other than that, this PR seems to do sane things.

 - @ark3 Do you want to lift b42e55c and d655c26 over to apro.git? You surely know what those scripts are doing better than I do.
 - @kflynn Do you want to figure out something sane around the info in `apro.version` making it in to `VERSION.py`?

**Comment by ark3** [comment]
Yes, I'll add the appropriate stuff to apro.git to build Edge Control for Linux and MacOS. Thank you.

**Comment by LukeShu** [comment]
Flynn says hacking up VERSIONS.py is a rabbit hole, and to have APro's `post-compile.sh` overwrite `ambassador.version` for now.

**Comment by LukeShu** [comment]
https://github.com/datawire/apro/pull/461

**Comment by LukeShu** [comment]
I'll wait for CI to finish on both, then click merge on both?

**Pull request merged**
