### PR TITLE
Refactor estats update

### PR DESCRIPTION
**Pull request by jfrabaute**
## Description
Refactor EnvoyStats
EnvoyStats has been split into two objects so using the stats by clients guarantees immutability

### CODE REVIEW

**Comment by kflynn** [comment]
Hey @jfrabaute, can you merge `master` into this so we can try for a clean CI run? 🙂

**Comment by kflynn** [comment]
Oh wait -- mea culpa! Let me restart the test, you already did rebase. 🙄

**Comment by kflynn** [comment]
🙂  Looks like this still has some trouble:

```
KubeStatus DONE 80: result cluster-tag-4.default: update OK
KubeStatus DONE 80: result cluster-tag-1.default: update OK
2020-06-04 13:58:35 diagd 1.5.0-citest.2-60-g214fc670e-dirty [P80TThreadPoolExecutor-0_1] ERROR: Exception on /ambassador/v0/check_ready [GET]
Traceback (most recent call last):
  File "/usr/lib/python3.7/site-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/lib/python3.7/site-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/lib/python3.7/site-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/lib/python3.7/site-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/usr/lib/python3.7/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/lib/python3.7/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/usr/lib/python3.7/site-packages/ambassador-0.0.0.dev0-py3.7.egg/ambassador_diag/diagd.py", line 507, in check_ready
    status = envoy_status(app.estats_mgr.get_stats())
  File "/usr/lib/python3.7/site-packages/ambassador-0.0.0.dev0-py3.7.egg/ambassador_diag/diagd.py", line 378, in envoy_status
    since_boot = interval_format(estats.time_since_boot(), "%s", "less than a second")
AttributeError: 'dict' object has no attribute 'time_since_boot'
2020-06-04 13:58:43 diagd 1.5.0-citest.2-60-g214fc670e-dirty [P80TThreadPoolExecutor-0_5] ERROR: Exception on /ambassador/v0/check_alive [GET]
Traceback (most recent call last):
  File "/usr/lib/python3.7/site-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/lib/python3.7/site-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/lib/python3.7/site-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/lib/python3.7/site-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/usr/lib/python3.7/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/lib/python3.7/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/usr/lib/python3.7/site-packages/ambassador-0.0.0.dev0-py3.7.egg/ambassador_diag/diagd.py", line 494, in check_alive
    status = envoy_status(app_mgr.get_stats())
NameError: name 'app_mgr' is not defined
2020-06-04 13:58:45 diagd 1.5.0-citest.2-60-g214fc670e-dirty [P80TThreadPoolExecutor-0_0] ERROR: Exception on /ambassador/v0/check_ready [GET]
Traceback (most recent call last):
  File "/usr/lib/python3.7/site-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/lib/python3.7/site-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/lib/python3.7/site-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/lib/python3.7/site-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/usr/lib/python3.7/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/lib/python3.7/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/usr/lib/python3.7/site-packages/ambassador-0.0.0.dev0-py3.7.egg/ambassador_diag/diagd.py", line 507, in check_ready
    status = envoy_status(app.estats_mgr.get_stats())
  File "/usr/lib/python3.7/site-packages/ambassador-0.0.0.dev0-py3.7.egg/ambassador_diag/diagd.py", line 378, in envoy_status
    since_boot = interval_format(estats.time_since_boot(), "%s", "less than a second")
AttributeError: 'dict' object has no attribute 'time_since_boot'
```

To test locally:

1. Have a Kubernetes cluster, with `KUBECONFIG` set correctly.
2. Set `DEV_KUBECONFIG` to the same thing as `KUBECONFIG`.
3. `make clobber push pytest-only KAT_RUN_MODE=envoy PYTEST_ARGS="-k Lua"`

That'll run just the Lua test, which is the simplest non-empty test. Then you can use `kubectl logs luatest` to see what happens.

**Comment by jfrabaute** [comment]
Not stale

**Comment by kflynn** [comment]
Subsumed by 4f426ec -- thanks!! This was an important piece of that commit. 🙂

**Pull request closed without merging**
