### PR TITLE
Allow HTTP/1.0

### PR DESCRIPTION
**Pull request by ryanmaclean**
This is required for cloud-based load balancer health checks that use HTTP 1.0.

## Description
Accept HTTP 1.0 traffic

## Related Issues
This relates to #988 - all credit to @phenoxim !

## Testing
Tests passed aside from 4 warnings which were present in the master branch as well. 

## Todos
- [ ] Tests
- [x] Documentation (happy to help here, just point me in the right direction!)

## Other
* If this is a documentation change, please open the pull request against the `stable` branch.
* Code changes should occur against `stable`.

### CODE REVIEW

**Comment by ryanmaclean** [comment]
Looks like the build failed with: 

```
openssl aes-256-cbc \
    -K $encrypted_21b00a486c76_key \
    -iv $encrypted_21b00a486c76_iv \
    -in releng/kubernaut_v2_config.enc \
    -out ~/.config/kubernaut/config \
    -d

iv undefined
```

**Comment by richarddli** [comment]
Thanks! That's a known problem with external contribs (we're working on fixing that -- it's because we don't expose secrets outside of the org).

Regarding docs, I think this should go here:

https://github.com/datawire/ambassador/blob/master/docs/reference/core/ambassador.md

(Is it in the Ambassador module?)

We list the different options in alphabetical order.

**Comment by ryanmaclean** [comment]
@richarddli - will have a look at the docs and see if anything's needed!

**Comment by ryanmaclean** [comment]
Ah interesting - I hadn't stumbled across this file yet! @richarddli would it be better to implement this as enabled by default, and handle it using a conf change? I was being optimistic in that I don't see harm in enabling it by default, but now see that may not be the desired approach.

**Comment by richarddli** [comment]
Generally speaking we disable new things like this by default because we have tens of thousands of folks running in prod now, so we try to be fairly conservative on changing defaults (and we announce in advance breaking changes). E.g., the grpc_web support is false by default.

**Comment by ryanmaclean** [comment]
@richarddli that's exactly what I was looking at the, the grpc section. I'll see if I can find where that is called in order to use the same pattern. Would that work?

**Comment by richarddli** [comment]
Yes, that'd be great! Thanks!

**Comment by cyrus-mc** [comment]
@ryanmaclean PR-1484 implements this functionality but does it via a configuration option on the Ambassador module.

**Comment by ryanmaclean** [comment]
Thanks @cyrus-mc !

**Pull request closed without merging**
