### PR TITLE
be able to configure envoy for ipv6 support

### PR DESCRIPTION
**Pull request by vangheem**
## Description

To be able to run envoy with ipv6

## Related Issues
diag still not supported

## Testing

Deployed and ran on cluster

## Todos
- [ ] Tests? Do I need to write tests for this?
- [x] Documentation

### CODE REVIEW

**Comment by kflynn** [comment]
Hey, so this looks really cool! (Sorry for the delay responding, had a bunch of testing issues to unravel recently.)

How are you setting up your cluster to support IPv6?

Simplest thing to do for `diagd` might just be to modify it such that if no `--host` is passed in, it binds to `INADDR_ANY` and catches both IPv4 and IPv6; have you tried that, by any chance?

Thanks again!

**Comment by vangheem** [comment]
I have not even tried to setup diagd for it yet--we just need envoy to work correctly.

Do I need to rebase this so tests pass?

**Comment by kflynn** [comment]
Yes, we'll need to get tests passing and we'll need to get `diagd` working before taking it.

I'm also really curious about how you're setting up Kubernetes for IPv6 because I want to start playing with this in-house. :wink:

**Comment by vangheem** [comment]
I have no idea how to manually setup k8s for ipv6... I have an existing cluster that was setup for me that I'm doing testing on.

**Pull request closed without merging**
