### PR TITLE
Add support for gRPC-Web using Envoy's grpc_web filter

### PR DESCRIPTION
**Pull request by gertvdijk**
For more information, please refer to [Envoy's docs](https://www.envoyproxy.io/docs/envoy/v1.9.0/configuration/http_filters/grpc_web_filter#config-http-filters-grpc-web).

Thanks to @rotemtam for the original implementation with the gRPC HTTP/1.1 bridge in #1201 for making this so trivial for me to contribute!

Implements feature request #456.

**(Did not have time to test this yet -- if anyone could do it, that would be great! But currently I can't really test it in my setup due to unrelated issue #1203.)**

### CODE REVIEW

**Comment by gertvdijk** [comment]
I see a failure on Travis and I have no clue how that's related to my change. Any pointers?

**Comment by kflynn** [comment]
Your Travis failure is indeed unrelated. I'll see if I can fix that shortly.

In the meantime, as noted in #1201, we'll need docs for this! :smile: And KAT tests, but those are blocked on some GRPC work on our end which will hopefully be resolved soon.

Thanks much!!

**Comment by gertvdijk** [comment]
> we'll need docs for this!

Yeah, but what would you like to see? It currently contains a few lines in there. I would love to help out and write a bit more. :smile: 

> And KAT tests, but those are blocked on some GRPC work on our end

What are KAT tests exactly? A kind of integration test? If so, what would you like to see covered? If the filter is set in Envoy, that's all you need from an Ambassador perspective, no?

**Comment by richarddli** [comment]
> What are KAT tests exactly? A kind of integration test? If so, what would you like to see covered? If the filter is set in Envoy, that's all you need from an Ambassador perspective, no?

The KAT tests are explained here: https://github.com/datawire/ambassador/tree/master/kat. They're designed to catch a few different categories of bugs:

1. Regressions in Envoy, or its configuration. (This happens more often than you might expect.) We want to make sure that functionality still works even when we upgrade our base Envoy version.
2. Issues in combining different parameters, e.g., say you want to set a `timeout_ms` along with the gRPC filter.

It's unlikely that there are bugs in the "happy path" case but we've learned the hard way that the boundary cases are what necessitate more rigorous testing.

Will defer to @kflynn as to whether or not we want to merge this without KAT tests. Related is #1217.

**Comment by kflynn** [comment]
@gertvdijk Looks like I introduced conflicts when I took #1201 -- if you can clean those up I'll take this one too, without tests since @gsagula wants some things to use to test his gRPC testing work. :wink:

**Comment by gertvdijk** [comment]
@kflynn 
Please tell me I'm seeing things the wrong way here.

This PR was not merged due to insufficient updates to docs and the absence of 'KAT tests', but now the obsolete solution in #1201 (obsolete because see discussion there), without any docs and also without KAT tests. Hmm. That feels very much discouraging towards me. :disappointed: 

I'd also like to hear why someone (@gsagula) is apparently working on some obsolete HTTP bridge stuff and why this can't be in an experimental branch.

If I would update this PR I will include a revert of the changes in #1201 as it would not make any sense to keep them in both.

**Comment by richarddli** [comment]
@gertvdijk Please don't take this personally!  @gsagula is working on adding gRPC support to our automated test infrastructure, and so for a real-world exercise of the work he's doing, we wanted to merge both of the gRPC PRs so we could write tests ourselves. We merged the PRs sequentially (for no specific reason), and as such this one got caught up with conflicts. But we didn't see any real reason not to merge both.

**Comment by variantf** [comment]
Looking forward to this PR! What's the status for now and if there's anything I can contribute to?

**Comment by kflynn** [comment]
Merged a local copy of this with conflicts fixed -- thanks, @gertvdijk!

**Pull request closed without merging**
