### PR TITLE
Add support for adding headers to send to external auth services in AuthService

### PR DESCRIPTION
**Pull request by jasonewang**
## Description
Add support for adding headers to send to external auth services. 

## Related Issues
https://github.com/datawire/ambassador/issues/1764

## Testing
Manually tested by building an image and configuring `add_auth_headers`.

## Tasks That Must Be Done
- [x] Did you add or update tests?
- [x] Did you update documentation?

## Other
* If this is a documentation change for a particular release, please open the pull request against the release branch.

### CODE REVIEW

**Comment by jasonewang** [comment]
Not sure if I've missed something for the build step but seems to be complaining that a credential isn't set.

**Comment by kflynn** [comment]
So first off -- yeah, we're fixing the credential. 🙁  Sorry about that! 

But it looks like you missed the schema update: 

```
2020-06-01 20:22:50 diagd 1.5.0-47-g60774848c-dirty [P75TAEW] INFO: error authenticationhttpbufferedtest.default.3 not a valid AuthService: Additional properties are not allowed ('add_auth_headers' was unexpected)
```

You can run the test locally by:

1. Get a cluster set up.
2. Set `DEV_KUBECONFIG` with the same value as your `KUBECONFIG`.
3. `make push pytest-only KAT_RUN_MODE=envoy PYTEST_ARGS="-k Auth"`
4. Once that succeeds, `make pytest-gold`.

Thanks!!

**Comment by jasonewang** [comment]
> But it looks like you missed the schema update:
> 
> ```
> 2020-06-01 20:22:50 diagd 1.5.0-47-g60774848c-dirty [P75TAEW] INFO: error authenticationhttpbufferedtest.default.3 not a valid AuthService: Additional properties are not allowed ('add_auth_headers' was unexpected)
> ```

I missed that the test case that I expanded uses the v1 schema while I modified the v2 schema.

I read in another PR that (some?) v1 schemas are frozen. Should I instead expand the ext_auth test that uses the v2 schema or also update the v1 schema?

**Comment by kflynn** [comment]
Ahhh right. Yes, the `v1` schemas are frozen, and yes, it's fine to expand a `v2` test case. 🙂  Also, if you merge `master` into your PR again, CI should run the tests for you. 🙂

**Comment by jasonewang** [comment]
Thanks for the help. The build is passing now and this PR is ready for review.

**Pull request merged**
