### PR TITLE
Fixed invalid yaml in istio 1.5 documentation

### PR DESCRIPTION
**Pull request by xlanor**
## Description
There was a sample yaml file in #2758 for istio that was invalid, I removed the + signs in front of some components in the yaml file to correct the invalid yaml error 

## Tasks That Must Be Done
- [ ] Did you update CHANGELOG.md?
- [ ] Did you add or update tests?
- [X] Did you update documentation?
- [ ] Were there any special dev tricks you had to use to work on this code efficiently?
  + [ ] Did you add them to DEVELOPING.md?
- [ ] Is this a build change?
  + [ ] If so, did you test on both Mac and Linux?

## Other
* If this is a documentation change for a particular release, please open the pull request against the release branch.

### CODE REVIEW

**Comment by richarddli** [comment]
Thanks! We had left the `+` in there on purpose to highlight the changes necessary to the YAML, but perhaps this was confusing in the end?

Were you able to successfully get Istio 1.5 working following the instructions?

**Comment by xlanor** [comment]
Thanks Richard!

I'm running into other issues with istio 1.6.4, but I'll get back to you once I have more accurately narrowed down the source of the problem!

**Comment by kflynn** [comment]
@ppeble, a second pair of eyes here would be welcome. 🙂

**Comment by ppeble** [comment]
This looks good to me. It is definitely valid YAML now, I just linted it to confirm. 👍

**Pull request merged**
