### PR TITLE
Update tls-termination.md, added a small note to help other people setting up tls with multiple ambassador instances running in one cluster.

### PR DESCRIPTION
**Pull request by michaelsovik**
This should be documented somewhere, not sure if this is the right place, but a least this would have helped me.

## Description
A few sentences describing the overall goals of the pull request's commits.

## Related Issues
List related issues.

## Testing
A few sentences describing what testing you've done, e.g., manual tests, automated tests, deployed in production, etc.

## Tasks That Must Be Done
- [ ] Did you update CHANGELOG.md?
- [ ] Did you add or update tests?
- [ ] Did you update documentation?
- [ ] Were there any special dev tricks you had to use to work on this code efficiently?
  + [ ] Did you add them to DEVELOPING.md?
- [ ] Is this a build change?
  + [ ] If so, did you test on both Mac and Linux?

## Other
* If this is a documentation change for a particular release, please open the pull request against the release branch.

### CODE REVIEW

**Comment by michaelsovik** [comment]
I don't really care if you guys accept this pull request, but someone should add some documentation on this somewhere.

**Comment by richarddli** [comment]
Thank you! Do you think https://www.getambassador.io/docs/latest/topics/running/running/#ambassador_id would make more sense?

**Comment by michaelsovik** [comment]
Hey Richard, that probably makes more sense. Thank you :)

**Comment by kflynn** [comment]
(Since this PR was into `master`, this won't appear in the live docs until later this week.)

**Pull request merged**
