### PR TITLE
handle TimeoutExpired on envoy validation, to keep receiving config updates

### PR DESCRIPTION
**Pull request by jwm**
## Description
When `envoy --mode validate` fails, Ambassador receives an unhandled `subprocess.TimeoutExpired` and stops picking up all future configuration changes.

This adds retries to Envoy config validation, in the fervent hope that a subsequent validation will not time out.

## Related Issues
#1478

## Testing
We were hitting `TimeoutExpired` a few times per day. We're running this branch in production, and are waiting for the timeout case to hit to make sure the updates handle it correctly.

## Todos
- [ ] Tests -- not sure if there are any automated tests for this. I'm not too familiar with Ambassador's code base, but looking at previous revisions that touched this code, it doesn't look like there are any tests to be updated.
- [X] Documentation -- think this change is pretty transparent, having Ambassador DTRT.

### CODE REVIEW

**Comment by jwm** [comment]
Also, WDYT about increasing the timeout here, maybe to `10s`? Feels like it would help Ambassador continue on with important management plane activity in the face of CPU contention.

Our current `envoy.json` is ~150k and takes ~750msec on average to validate, with spikes that correlate highly to load causing timeouts 5-10 times/day.

**Comment by richarddli** [comment]
Thanks for tracking this down! How many services do you have and do you mind characterizing what type of load you're seeing? I'm a little surprised that traffic spikes can cause these issues, but find it completely believable. (And also FTR we're based in South Station, Boston, if you want to come over sometime for some swag!)

**Comment by kflynn** [comment]
@jwm Let me second @richarddli's invitation -- if you're hitting this multiple times a day, I _definitely_ want to talk to you about your setup.

**Comment by kflynn** [comment]
@jwm Code looks good. I'm fine with bumping the timeout (and/or making it configurable) -- how's it looking running at your shop?

**Comment by jwm** [comment]
Hi @richarddli @kflynn, thanks for responding so quickly! Before this gig, I worked near Summer and A Streets. I'll have to make a point to drop by sometime. :-)

Our config renders into a ~dozen Envoy clusters and 2 listeners. Our primary listener has a dozen or so filter chain entries. `envoy.json` is about 150kbytes. Traffic volume is fairly light (10-20 QPS at peak).

One thing I just realized I should mention: we're running Ambassador as a `DaemonSet` with `Burstable` QoS, with a CPU request of `100m` and a limit of `500m`. I wouldn't be surprised at all that intermittent CPU starvation is a factor here, and I've been starting to think this is a suboptimal deployment strategy. We're just moving this workload to k8s, and there are a number of things we're shuffling around as we find our way.

The lightly trafficked environment I deployed these changes to hasn't hit a timeout yet. I'll move our production environment to it hopefully tonight. I'll let you know how it goes!

**Comment by nicolasbelanger** [comment]
FYI... Got bitten by the same issue.  We were using 100m for both limits and requests cpu.  Bumping limit to 1 (1000m) and it's mostly problem solved.

**Comment by jwm** [comment]
@richarddli @kflynn These changes have been fine here for the last few days, but we haven't triggered the configuration validation timeout since we bumped the CPU resource reservations on Ambassador pods. I can bump them down in one of our envs to double check, but I think the code is fine.

Beyond that, it looks like the [Travis build is failing](https://travis-ci.org/datawire/ambassador/builds/551367624#L1690):

```
Checking 336 url requirements... 322 not ready (http://ambassadoridtest-http: Get http://ambassadoridtest-http: net/http: request canceled (Client.Timeout exceeded while awaiting headers)) sleeping 10s...
```

I'll plan on setting up a local environment to run the test suite, but probably won't get to it in earnest until next week because of the holiday and trying to [figure out the `503 NR`s in Envoy we're experiencing](https://datawire-oss.slack.com/archives/CAULN7S76/p1562013430015900).

**Pull request merged**
