### PR TITLE
 added Header based routing and Cross-Origin Resource Sharing section…

### PR DESCRIPTION
**Pull request by sai3010**
… in the CORS document

## Description
Added Header based routing and Cross-Origin Resource Sharing section in the cors.md document so that confusion is avoided while using CORS and header-based routing together.

# Note
This is just a document update to give better clarity while implementing CORS in ambassador.

### CODE REVIEW

**Comment by nbkrause** [comment]
@sai3010 Thank you for submitting this PR.

I am a little confused what it is trying to accomplish though as I am not able to replicate any issue with the `Mapping` you provided that does not work. Are you expecting Ambassador to respond to an OPTIONS request that does not have the `x-quote-mode` header? Setting `headers` in a `Mapping` means that the request **must** have the headers specified for it to match the route in Ambassador.

We love our users to contribute documentation when things are confusing. I think with some clarifications on what you are trying to communicate, we would be happy to take this.

**Comment by sai3010** [comment]
Hey, thanks for your feedback. Let me clarify this, say  you are using header based routing in order to route request to a service, the service throws CORS error. In order to fix this we need to add CORS configuration to this particular mapping when we do this for some reason envoy does not take into consideration the ```headers``` under CORS configuration when its used along with header based routing. This issue I faced it realtime and hence thought of adding this as a part of documentation so that it will be more clear. The yamls that I have added are just for reference. I hope this clarifies this PR.

**Comment by sai3010** [comment]
@nbkrause any update on this?

**Comment by sai3010** [comment]
@nbkrause could you please update?

**Comment by nbkrause** [comment]
Hi Sai,

I guess I am confused since I am not seeing this behavior.

If I have the following `Mapping`:
```
apiVersion: getambassador.io/v2
kind: Mapping
metadata:
  annotations:
  name: service1
  namespace: default
spec:
  cors:
    headers: Content-Type, x-quote-mode
    methods: POST, GET, OPTIONS
    origins: http://foo.example.com,http://bar.example.com
  headers:
    x-quote-mode: backend
  prefix: /api/
  service: quote.default
```

Ambassador configures the following Envoy `route` which matches based off the `prefix: /api/` and header `x-quote-mode: backend` and then sends the request to the cors filter as I would expect it to:
```
                                                    {
                                                        "match": {
                                                            "case_sensitive": true,
                                                            "headers": [
                                                                {
                                                                    "exact_match": "backend",
                                                                    "name": "x-quote-mode"
                                                                },
                                                                {
                                                                    "exact_match": "https",
                                                                    "name": "x-forwarded-proto"
                                                                }
                                                            ],
                                                            "prefix": "/api/",
                                                            "runtime_fraction": {
                                                                "default_value": {
                                                                    "denominator": "HUNDRED",
                                                                    "numerator": 100
                                                                },
                                                                "runtime_key": "routing.traffic_shift.cluster_quote_default_default"
                                                            }
                                                        },
                                                        "route": {
                                                            "cluster": "cluster_quote_default_default",
                                                            "cors": {
                                                                "allow_headers": "Content-Type, x-quote-mode",
                                                                "allow_methods": "POST, GET, OPTIONS",
                                                                "allow_origin_string_match": [
                                                                    {
                                                                        "exact": "http://foo.example.com"
                                                                    },
                                                                    {
                                                                        "exact": "http://bar.example.com"
                                                                    }
                                                                ],
                                                                "filter_enabled": {
                                                                    "default_value": {
                                                                        "denominator": "HUNDRED",
                                                                        "numerator": 100
                                                                    },
                                                                    "runtime_key": "routing.cors_enabled.5e46e54f662a7a193da18a8d959da67b69775a5e"
                                                                }
                                                            },
                                                            "prefix_rewrite": "/",
                                                            "priority": null,
                                                            "timeout": "3.000s"
                                                        }
                                                    },
```

I then can send the following curls and get the result I would expect to:
```
curl -vk https://foo.example.com/api/debug/ -H "x-quote-mode: backend" -H "Origin: http://foo.example.com" -H "Access-Control-Request-Method: GET" -X OPTIONS -H "Access-Control-Request-Headers: x-quote-mode"
*   Trying 35.222.20.161:443...
* Connected to foo.example.com (35.222.20.161) port 443 (#0)
> OPTIONS /api/debug/ HTTP/1.1
> Host: foo.example
> User-Agent: curl/7.69.1
> Accept: */*
> x-quote-mode: backend
> Origin: http://foo.example.com
> Access-Control-Request-Method: GET
> Access-Control-Request-Headers: x-quote-mode
>
* Mark bundle as not supporting multiuse
< HTTP/1.1 200 OK
< access-control-allow-origin: http://foo.example.com
< access-control-allow-methods: POST, GET, OPTIONS
< access-control-allow-headers: Content-Type, x-quote-mode
< date: Tue, 06 Oct 2020 14:07:50 GMT
< server: envoy
< content-length: 0
<
* Connection #0 to host foo.example.com left intact
```

```
curl -vk https://foo.example.com/api/debug/ -H "x-quote-mode: backend" -H "Origin: http://bar.example.com" -H "Access-Control-Request-Method: GET" -X OPTIONS -H "Access-Control-Request-Headers: x-quote-mode"
*   Trying 35.222.20.161:443...
* Connected to foo.example.com (35.222.20.161) port 443 (#0)
> OPTIONS /api/debug/ HTTP/1.1
> Host: foo.example
> User-Agent: curl/7.69.1
> Accept: */*
> x-quote-mode: backend
> Origin: http://bar.example.com
> Access-Control-Request-Method: GET
> Access-Control-Request-Headers: x-quote-mode
>
* Mark bundle as not supporting multiuse
< HTTP/1.1 200 OK
< access-control-allow-origin: http://bar.example.com
< access-control-allow-methods: POST, GET, OPTIONS
< access-control-allow-headers: Content-Type, x-quote-mode
< date: Tue, 06 Oct 2020 14:07:50 GMT
< server: envoy
< content-length: 0
<
* Connection #0 to host foo.example.com left intact
```

```
curl -vk https://foo.example.com/api/debug/ -H "Origin: http://foo.example.com" -H "Access-Control-Request-Method: GET" -X OPTIONS -H "Access-Control-Request-Headers: x-quote-mode"
*   Trying 35.222.20.161:443...
* Connected to foo.example.com (35.222.20.161) port 443 (#0)
> OPTIONS /api/debug/ HTTP/1.1
> Host: foo.example
> User-Agent: curl/7.69.1
> Accept: */*
> x-quote-mode: backend
> Origin: http://foo.example.com
> Access-Control-Request-Method: GET
> Access-Control-Request-Headers: x-quote-mode
>
* Mark bundle as not supporting multiuse
< HTTP/1.1 404 Not Found
< date: Tue, 06 Oct 2020 14:15:56 GMT
< server: envoy
< content-length: 0
<
* Connection #0 to host foo.example.com left intact
```

You can see that the requests are getting the expected cors response when the `x-quote-mode` header is included but gets a `404` if that header is not included.

Could you try with a more recent version of Ambassador? It is possible this has been fixed as part of some recent changes.

Sorry for the long delay in responding to this. I will follow this issue more closely if you would like to continue working with me.

**Pull request closed without merging**
