### PR TITLE
Set a capability to allow binding to low ports

### PR DESCRIPTION
**Pull request by swalberg**
## Description

The cap_net_bind_service capability allows a process to bind to a low
port without root. While Kubernetes lets you allow a capability in the
pod spec, the effective capabilities are wiped when the root -> user
transition is made.

This change `setcap`'s the binary so that it can assert that capability. e.g.
```
 securityContext:                                                                                                                                  |~
   capabilities:                                                                                                                                   |~
     add:                                                                                                                                          |~
       - NET_BIND_SERVICE
``` 
(there is no `CAP_` at the beginning; K8s seems to add that)

If you don't want to bind to a low port, don't add the capability and
we're back to the previous behavior. If you want to bind to a low port,
add the capability and configure Ambassador appropriately.

## Related Issues

This is a feature addition -- I want to be able to run this as a non root user but still bind to a low port.

## Testing

Manual testing.

## Todos
- [ ] Tests
- [ ] Documentation

### CODE REVIEW

**Comment by swalberg** [comment]
I am not sure what kind of tests are appropriate. If this PR is accepted I can update the documentation repo, too.

**Comment by kflynn** [comment]
Well, for testing, the simple route would be to modify an existing KAT test to add the capability and then use it.

Is there any downside to adding this capability, that you can think of?

**Comment by swalberg** [comment]
Hi @kflynn, no I can't see a downside. This capability is so specific (bind to a low port) and can only be used if the admin grants it.

**Comment by kflynn** [comment]
@swalberg Thanks, that sounds sane to me. How's your bandwidth looking for a test modification? :smile:

**Comment by swalberg** [comment]
On my todo list for this week ;)

**Comment by kflynn** [comment]
@swalberg Excellent! :smile: Yell if (when ;) ) you have questions.

**Comment by swalberg** [comment]
Just an update, I spent some time getting up to speed on those tests, should be able to figure the rest out next week.

**Comment by swalberg** [comment]
Can you have a peek at my second commit, please? I wrote what I think is a test but it's not failing when I think it should. Do I need to call it somewhere?

**Comment by kflynn** [comment]
Hmmm. I can tell you that the `Empty` test can't be duplicated in your `t_capabilities.py` file, but the rest looks like it should definitely fail. What happens when you do

```
make clobber docker-push test TEST_NAME=LowPort
```

??

**Comment by swalberg** [comment]
Won't bore you with the details, but that command helped me find a bunch of Python errors in my test. The test is running now, thanks!

**Comment by kflynn** [comment]
Cool! More commits coming, then? :smile:

**Comment by swalberg** [comment]
Either commits or more questions ;)

**Comment by kflynn** [comment]
Either is a win. :smile:

**Comment by swalberg** [comment]
I haven't forgotten about this... My current challenge seems to be that there's a hard coded NodePort to forward port 80 to the pod's 8080 in the `AMBASSADOR` kat manifest. That's fine, I can add an 82->80 mapping, but I don't see how the port gets set up in the pod. And when I run the test with `make DOCKER_REGISTRY=localhost:5000 USE_KUBERNAUT=false KUBECONFIG=~/.kube/config TEST_NAME=LowPort clobber docker-push test` it first tries to connect to the service on port 80 which is hard coded to 8080, but I've already told the pod to listen on 80.

```tarting requirements check (limit 300s)...
Checking 4 url requirements... 2 not ready (http://lowporttest/ambassador/v0/check_ready: Get http://lowporttest/ambassador/v0/check_ready: net/http: request canceled (Client.Timeout exceeded while awaiting headers)) sleeping 10s...
Checking 4 url requirements... 2 not ready (http://lowporttest/ambassador/v0/check_ready: Get http://lowporttest/ambassador/v0/check_ready: EOF) sleeping 10s...
Checking 4 url requirements... 2 not ready (http://lowporttest/ambassador/v0/check_ready: Get http://lowporttest/ambassador/v0/check_ready: read tcp 10.198.241.230:64525->10.108.202.209:80: read: connection reset by peer) sleeping 10s...


Checking 4 url requirements... 2 not ready (http://lowporttest/ambassador/v0/check_ready: Get http://lowporttest/ambassador/v0/check_ready: read tcp 10.198.241.230:64535->10.108.202.209:80: read: connection reset by peer) sleeping 10s...
```

```sean~$ kubectl get services
NAME                TYPE        CLUSTER-IP       EXTERNAL-IP   PORT(S)                                   AGE
kubernetes          ClusterIP   10.96.0.1        <none>        443/TCP                                   15d
lowporttest         NodePort    10.108.202.209   <none>        80:30624/TCP,443:31265/TCP,82:30693/TCP   8d
lowporttest-admin   NodePort    10.101.77.140    <none>        8877:31512/TCP                            8d
lowporttest-http    ClusterIP   10.110.167.167   <none>        80/TCP,443/TCP                            8d```

Thoughts?

**Comment by kflynn** [comment]
So I think what you want to do is:

- change `manifests.AMBASSADOR` so that
   - the `targetPort` in the `Service` definitions reflects your low port
   - the `Pod` definition has your capability
- change your `Ambassador` module to bind on the low port you want

and I think that'll do it. Ambassador will bind on the low port, but Kubernetes will do port-mapping magic so that none of the tests need to change otherwise.

**Comment by kflynn** [comment]
(Sorry for giving you a merge conflict! but you'll want to merge `master` into your branch anyway to get the shiny new CI goodness.)

**Comment by kflynn** [comment]
When I run your latest, the test fails with

```
ambassador-listener-81: cannot bind '0.0.0.0:81': Permission denied
```

🙁 

It looks like the manifest is correct though:

```
---
apiVersion: v1
kind: Pod
metadata:
  name: lowporttest
  annotations:
    sidecar.istio.io/inject: "false"
  labels:
    service: lowporttest
    kat-ambassador-id: lowporttest
    scope: AmbassadorTest
  namespace: default
spec:
  securityContext:
    runAsUser: 8888
  serviceAccountName: lowporttest
  restartPolicy: Always
  volumes:
  - name: scratchpad
    emptyDir:
      medium: Memory
      sizeLimit: "45Mi"
  containers:
  - name: ambassador
    image: dwflynn/ambassador:swalberg-capabilities-25530155-dirty
    ports:
    - containerPort: 81
    env:
    - name: AMBASSADOR_NAMESPACE
      valueFrom:
        fieldRef:
          fieldPath: metadata.namespace
    - name: AMBASSADOR_ID
      value: lowporttest
    - name: AMBASSADOR_SNAPSHOT_COUNT
      value: "0"
    - name: AMBASSADOR_CONFIG_BASE_DIR
      value: "/tmp/ambassador"
    securityContext:
      allowPrivilegeEscalation: false
      readOnlyRootFilesystem: true
      capabilities:
        add: ["NET_BIND_SERVICE"]
    livenessProbe:
      httpGet:
        path: /ambassador/v0/check_alive
        port: 8877
      initialDelaySeconds: 30
      periodSeconds: 10
      failureThreshold: 30
    readinessProbe:
      httpGet:
        path: /ambassador/v0/check_ready
        port: 8877
      initialDelaySeconds: 30
      periodSeconds: 10
      failureThreshold: 30
    volumeMounts:
    - mountPath: /tmp/
      name: scratchpad
```

**Comment by swalberg** [comment]
Yea, getting the same here. Trying to get it to run outside of the test again.

**Comment by swalberg** [comment]
```
bash-4.4$ getcap /usr/local/bin/envoy
/usr/local/bin/envoy = cap_net_bind_service+ep
bash-4.4$ grep Cap /proc/156/status
CapInh:	00000000a80425fb
CapPrm:	0000000000000000
CapEff:	0000000000000000
CapBnd:	00000000a80425fb
CapAmb:	0000000000000000
bash-4.4$ capsh --decode=00000000a80425fb
0x00000000a80425fb=cap_chown,cap_dac_override,cap_fowner,cap_fsetid,cap_kill,cap_setgid,cap_setuid,cap_setpcap,cap_net_bind_service,cap_net_raw,cap_sys_chroot,cap_mknod,cap_audit_write,cap_setfcap
``` 

ok it has `cap_net_bind`.

Ah, it's that `allowPrivilegeEscalation: false` that prevents the binary to use capabilities. I looked in our k8s environments and I don't see it there. If I set it to `true` I can bind to 81.

**Comment by kflynn** [comment]
I don't have a problem with a mod to `allowPrivilegeEscalation` for the `LowPort` test...

**Comment by swalberg** [comment]
I can't believe it, passing tests (at least locally)! Thanks!

(the test is that a call to http://localhost:80/ returns a 404 from Envoy, I figure the purpose of this test is to make sure Envoy is listening so that should be enough)

**Comment by swalberg** [comment]
BTW, assuming this all passes, I'm happy to squash and write a decent commit message if that's what you'd prefer in the history.

**Comment by kflynn** [comment]
Thanks! I was going to ask you to add docs, but realized that our current docs on running are.. uh... wrong. 😐 😆

**Comment by swalberg** [comment]
Can you point me to the docs you're talking about? Maybe I can make them less wrong.

**Comment by kflynn** [comment]
That would be wonderful! Look at `docs/reference/running.md` --

- Since Ambassador 0.60, the default ports have been 8080 and 8443 -- basically we've defaulted to assuming that you're running non-root without privilege escalation since 0.60, and our default published YAML (in `docs/yaml/ambassador`) includes a `securityContext` to run as user 8888.

- It would probably be worth a note that if you're running as non-root, you will most likely be _required_ to change `AMBASSADOR_CONFIG_BASE_DIR` as non-root may not be able to write in `/ambassador` (this goes double if you have a read-only root filesystem)

- Obviously there should be some discussion of using the capability to bind to a low port without being root. :wink:

- I would normally say to make the doc change as a PR against the `datawire/ambassador-docs` repo, but in this case the capability thing is a feature that has yet to ship, so the `datawire/ambassador` repo is correct.

Many thanks!!

**Pull request merged**
