### PR TITLE
Switch to -ea.N and -rc.N

### LINKED ISSUE #2211: Adjust all of the machinery to use -ea.N and -rc.N instead of -eaN and -rcN
We agreed that after 1.0.0, we would follow strict SemVer.  This means that our pre-release suffixes need to change from `-ea${N}` and `-rc${N}` to including a dot: `-ea.${N}` and `-rc.${N}`.  While the existing dotless versions are valid SemVer pre-release identifiers; they don't represent the information that we intend them to (thanks to OSS Sack user "yawniek" for pointing this out): They compare lexicographically, not numerically, which becomes a problem if we get in to the double-digits.  So while we expect that they sort as -ea8 < -ea9 < -ea10 < -ea11, SemVer actually says that they sort as -ea10 < -ea11 < -ea8 < -ea9, because '1' sorts before '8'.

There are a number of regexes that will need to be updated.

### PR DESCRIPTION
**Pull request by kflynn**
Instead of `-eaN` and `-rcN`, use `-ea.N` and `-rc.N`. 

Fixes #2211 for the `ambassador.git` side of the world.

### CODE REVIEW

**Comment by LukeShu** [comment]
I know RELEASING.md is hella out-of-date, but maybe adjust the examples in it?

**Comment by LukeShu** [comment]
GitHub won't let me attach a comment to the line, but the

```Makefile
if ! [[ "$$rc_latest" == "$(RELEASE_VERSION)"-rc* ]]; then \
```

on builder.mk line 235 should be changed to


```Makefile
if ! [[ "$$rc_latest" == "$(RELEASE_VERSION)"-rc.* ]]; then \
```

**Comment by LukeShu** [comment]
And update the comment on builder.sh line 134

**Comment by LukeShu** [comment]
And the check on builder.sh line 260

**Comment by LukeShu** [comment]
and the comment on builder/module_version.sh line 45

**Comment by LukeShu** [comment]
Does python/ambassador/ambscout.py need adjusted?

**Comment by kflynn** [comment]
Thanks for the catches! and yes, `ambscout.py` does have a check that I missed (because instead of `-(ea|rc)\d+` it was `-[A-Za-z_+]\d+` -- we should probably narrow that later).

**Pull request merged**
