### PR TITLE
Support TLS origination for auth-service

### PR DESCRIPTION
**Pull request by dvavili**
Add support to offer certificates to external auth-service. Adds a new field `tls: <Boolean|String>` similar to `Mapping`

### CODE REVIEW

**Comment by kflynn** [comment]
Looks good! Can you modify one of the test cases to test it?

**Comment by dvavili** [comment]
Done.

**Comment by dvavili** [comment]
CI seems to be failing because of invalid credentials to push, but the test case that I added passes.

**Comment by kflynn** [comment]
Yeah, gotta fix that CI hassle. Thanks!

**Pull request merged**
