### PR TITLE
Support enabling telemetry on gRPC calls

### PR DESCRIPTION
**Pull request by feliperoveran**
## Description
Support configuring the gRPC Statistics Envoy filter to enable telemetry on gRPC calls (https://www.envoyproxy.io/docs/envoy/latest/configuration/http/http_filters/grpc_stats_filter)

## Testing
There are automated tests for this feature.
To test manually, deploy a grpc service, configure ambassador to enable the grpc stats filter and check the prometheus metrics on `/metrics`

## Tasks That Must Be Done
- [X] Did you update CHANGELOG.md?
- [X] Did you add or update tests?
- [X] Did you update documentation?
- [ ] Were there any special dev tricks you had to use to work on this code efficiently?
  + [ ] Did you add them to DEVELOPING.md?
- [ ] Is this a build change?
  + [ ] If so, did you test on both Mac and Linux?

### CODE REVIEW

**Comment by djsly** [comment]
@alexgervais  in case you are looking for a side task ;)

**Comment by LukeShu** [comment]
Closing and re-opening the PR seems to have tickled CircleCI right to get it to run on the PR.

**Comment by feliperoveran** [comment]
@LukeShu could you please retrigger the pipeline? it seems like it's stuck again (and oss-dev-images failed starting up the kat pod)

**Comment by kflynn** [comment]
@feliperoveran How about merge `master` into your PR and fix conflicts? We've made changes to the underlying CI system that should fix the things you're seeing. 🙂

**Comment by djsly** [comment]
thanks @kflynn , we will have a look today to making this pass. 

Once it passes and this gets merged, when should we expect a release ? do you have weekly planned releases ?

**Comment by kflynn** [comment]
@djsly Looking forward to seeing this one moving. 🙂  The plan is for this to ship with 1.9.0, which is still some weeks out (you'll appreciate that it's dangerous for me to commit to specific dates 😂 ). We'd certainly be open to handing over a CI-built image if you want to make sure that our build works as well as yours?

**Comment by djsly** [comment]
The issue is that we are still. 0.86 and need to move quick to 1.X. 

This Pr is a blocker for our upgrade right now :( 

We are using an in-house image based on 0.86

I’ll make sure we unblock this PR quickly 

Thanks !

**Comment by feliperoveran** [comment]
@kflynn rebased! it should be ready to go :)

**Review by kflynn — APPROVED** [review]
Looks good, thanks much for the contribution and for sticking with it through all the CI hassles! 🙂

**Pull request merged**
