### PR TITLE
[WIP] Fix go warnings

### PR DESCRIPTION
**Pull request by brucehorn**
First pass on fixing some of the Go warnings that I see in edgectl.  Please take a close look to make sure that I haven't inadvertently changed any of the semantics (esp. in the defer statements).

### CODE REVIEW

**Comment by brucehorn** [comment]
Reset to merge to master.  Note that 2520 was branched off of this PR so the diffs will change for 2520 when this is merged.

**Comment by brucehorn** [comment]
will wait until #2520 has been merged to master and then resubmit.

**Comment by khussey** [comment]
@inercia please push changed to address the warnings that @brucehorn brought to your attention, thanks.

**Comment by khussey** [comment]
Closing this for now. We can put up a new PR when we get a chance to revisit this.

**Pull request closed without merging**
