### PR TITLE
Make sure correct namespace is attached to l5d-dst-override header

### PR DESCRIPTION
**Pull request by ricky26**
## Description
This PR moves namespace qualification of service names earlier (during IR mapping construction).

I figured this was better than repeating the logic from the endpoint generation (after all, the address we're referring to can happily contain the namespace, it shouldn't affect resolution elsewhere). Please give me a shout if you think this should be done another way, I'm happy to rework and clean up. :)

I've committed all of the gold output changes, since this PR does change the behaviour in some cases and I thought it warranted discussion.
- e.g. in the case of TCP mappings, the address generated in the endpoints would always contain the resolved service name with namespace, whereas if it matches the ambassador namespace, I now leave it unqualified.

## Related Issues
- #2302 - resolved by this PR because the `l5d-dst-override` header is now always populated with a qualified service name.

## Testing
I've added an additional Python test which ensures that the `l5d-dst-override` header contains the namespace when it is not fully-qualified and in a different namespace to ambassador.

## Todos
- [x] Tests

### CODE REVIEW

**Comment by ricky26** [comment]
I noticed too late that I hadn't rebased onto master - I'll do that when I get a moment!

**Comment by kflynn** [comment]
Hey @riky26 -- think you can tackle conflict resolution here? I'd suggest:

- rebase onto `master`, but ignore the `python/tests/gold` files
- `make clean push pytest-only KAT_RUN_MODE=envoy`
- Assuming that passes, `make pytest-gold`

Then we can get this landed. Thanks! and sorry for the delay!

**Comment by ricky26** [comment]
@kflynn okay, I've done the rebase.

The error from Travis is: `./releng/travis-script.sh: line 69: DOCKER_BUILD_PASSWORD: unbound variable`. This looks like a CI issue?

**Comment by ricky26** [comment]
@kflynn any update on being able to merge this?

**Comment by kflynn** [comment]
Augh, how did I miss this? 🙁  Mea culpa! If you can get the conflicts resolved, I'll get this landed. (If not I'll take a crack at it. 🙂 )

**Comment by ricky26** [comment]
I'm happy to have a go at the conflicts. Mostly it looks like the test result changes, which I can just regenerate. :)

**Comment by kflynn** [comment]
Awesome, thanks! 🙂

**Comment by ricky26** [comment]
@kflynn okay, done! (And I've just noticed that my first commit has a typo in... not sure I want to anger the CI gods at this point though...)

**Comment by kflynn** [comment]
Thanks! 🙂

**Pull request merged**
