### PR TITLE
styles, getting-started.js file for QuickStart page

### PR DESCRIPTION
**Pull request by cindymullins-dw**
New Quick Start page

## Related Issues
List related issues.

## Testing
A few sentences describing what testing you've done, e.g., manual tests, automated tests, deployed in production, etc.

## Tasks That Must Be Done
- [ ] Did you update CHANGELOG.md?
- [ ] Did you add or update tests?
- [ ] Did you update documentation?
- [ ] Were there any special dev tricks you had to use to work on this code efficiently?
  + [ ] Did you add them to DEVELOPING.md?

## Other
* If this is a documentation change for a particular release, please open the pull request against the release branch.
Screen Shot 2020-04-13 at 8 08 43 AM
Screenshot_2020-04-13 Docs Ambassador

### CODE REVIEW

**Comment by khussey** [comment]
Thanks, @cindymullins-dw, se attached images for how it looks on my computer (Chrome) and my iPhone (Safari).

computer

iPhone

**Comment by cindymullins-dw** [comment]
* Page with "Want to view install instructions?" link under Rectangle 3, and 
* drop down menu on Index page so user can jump to relevant install section..

screenshot 4-15

screenshot 2 4-15

After-the-jump example
Jump examamle 4-15

**Comment by khussey** [comment]
@cindymullins-dw here's what the latest preview looks like on my phone, in portrait and landscape mode.

portrait

landscape

**Comment by cindymullins-dw** [comment]
"Try to fix yaml link" commit fixed the problem.  This is the link in question and it now directs to the QuickStart page. 
fixed yaml link

**Comment by LukeShu** [comment]
Firefox 75.0 on X11: Screenshot_2020-04-16 Docs Ambassador

The "Copy" button sets the X11 CLIPBOARD selection to the given text, but not the PRIMARY selection; which means that middle-click paste doesn't work (this is something many many X11 users expect to work). (But that's always been the case that our Copy button works that way.)

The links all seem to work.

**Pull request merged**
