### PR TITLE
Build enovy-static with optimizations by default

### PR DESCRIPTION
**Pull request by esmet**
## Description
Build envoy with optimizations for performance. Allow a user to set ENVOY_COMPILATION_MODE to override the build type passed to bazel. For example, ENVOY_COMPILATION_MODE=dbg will produce a debug binary.

### CODE REVIEW

**Comment by kflynn** [comment]
Hey @LukeShu, can you poke at this? I'm thinking we land it, but it seems to dovetail with stuff you're poking at...

**Comment by LukeShu** [comment]
Can we rename `ENVOY_BUILD_STYLE` to `ENVOY_COMPILATION_MODE` (since `-c` is the short form of [`--compilation_mode`](https://docs.bazel.build/versions/master/user-manual.html#flag--compilation_mode)?

Otherwise, LGTM. I'll run a load-test against this either today or Monday.

**Comment by esmet** [comment]
> Can we rename `ENVOY_BUILD_STYLE` to `ENVOY_COMPILATION_MODE` (since `-c` is the short form of [`--compilation_mode`](https://docs.bazel.build/versions/master/user-manual.html#flag--compilation_mode))?
> 
> Otherwise, LGTM. I'll run a load-test against this either today or Monday.

Done

**Comment by kflynn** [comment]
Closed in favor of #1699.

**Pull request closed without merging**
