### PR TITLE
Move service and endpoints processing to a separate processor

### PR DESCRIPTION
**Pull request by impl**
## Description
This change moves service processing from the resource fetcher to a separate processor, `ServiceProcessor`. The functionality should be exactly the same.

## Testing
This passes the automated test suite.

## Tasks That Must Be Done
- [ ] Did you update CHANGELOG.md?
- [x] Did you add or update tests?
- [ ] Did you update documentation?
- [ ] Were there any special dev tricks you had to use to work on this code efficiently?
  + [ ] Did you add them to DEVELOPING.md?
- [ ] Is this a build change?
  + [ ] If so, did you test on both Mac and Linux?

### CODE REVIEW

**Comment by kflynn** [comment]
Also, yes, I know, we keep making more conflicts for you. Sorry. 😐 Let's talk (on Slack if it's easier) and get this landed. 😉

**Comment by impl** [comment]
There's an explanation of why ClusterIngress was removed on [this commit](https://github.com/datawire/ambassador/pull/2761/commits/3f492e6a123562b6918d13ede1b0f007bbda6909), but gist of it is that ClusterIngress was removed from Knative in version 0.9 and the ingress controller annotation we look for was added in 0.10 so there's no way a compatible Knative installation could be using ClusterIngress even before this change.

**Comment by kflynn** [comment]
...well. After conflicts are resolved. Again. 😂  Sorry about that.

**Review by kflynn — APPROVED** [review]
Looks good -- going to land this. Thanks, @impl!

**Pull request merged**
