### PR TITLE
added weighting to mirror feature in envoy

### PR DESCRIPTION
**Pull request by nemo83**
## Description
Shadowing traffic is a great feature, but not being able to select only a percentage of the traffic, forces the ghost service to be able to hold the full production traffic.

Envoy supports mirror traffic control via the [runtime_fraction](https://www.envoyproxy.io/docs/envoy/latest/api-v2/api/v2/route/route.proto.html?highlight=request_mirror_policy#route-routeaction-requestmirrorpolicy) property.

## Related Issues
N/A

## Testing
Manual testing done locally

## Todos
Added a couple of lines of documentation and one example.

## Other
* If this is a documentation change, please open the pull request at https://github.com/datawire/ambassador-docs instead.
* Code changes should occur against `master`.

### CODE REVIEW

**Comment by kflynn** [comment]
Looks good! There's an existing shadow test in `ambassador/tests/t_shadow.py` (which uses the shadow service from, I'm sad to say, `unused-e2e/shadow-service` -- think you can extend that to include weighting?

Thanks!

**Comment by nemo83** [comment]
hi @kflynn thanks for the feedback. I'm gonna try to setup my python env to implement/extend the test. Will I need kubernau to test that thing? Or will it be enough to setup pyenv?

**Comment by nemo83** [comment]
I seem to have hit an issue with Teleproxy where it cannot start on 

OS: `macosx mojave 10.14.4`
minikube version: v1.0.1
Kube: 1.10.13

Teleproxy logs:

```2019/05/03 20:35:55 starting setup-intercept
2019/05/03 20:35:55 cannot start setup-bridges, required worker missing: interceptor
2019/05/03 20:35:55 cannot start ready-notifier, required worker missing: interceptor
2019/05/03 20:35:55 starting signal-handler
2019/05/03 20:35:55 TPY: Automatically set -dns=89.101.160.4
2019/05/03 20:35:55 TPY: Automatically set -fallback=8.8.8.8
2019/05/03 20:35:55 cannot start setup-bridges, interceptor not ready
2019/05/03 20:35:55 cannot start ready-notifier, interceptor not ready
2019/05/03 20:35:55 starting interceptor
2019/05/03 20:35:55 starting api-server
2019/05/03 20:35:55 starting dns-server
2019/05/03 20:35:55 starting proxy-server
2019/05/03 20:35:55 cannot start search-override, interceptor not ready
2019/05/03 20:35:55 cannot start setup-bridges, interceptor not ready
2019/05/03 20:35:55 cannot start ready-notifier, interceptor not ready
2019/05/03 20:35:55 cannot start search-override, interceptor not ready
2019/05/03 20:35:55 TPY: initial rlimit: {4864 9223372036854775807}
2019/05/03 20:35:55 TPY: Final rlimit {49152 49152}
2019/05/03 20:35:55 PXY: listening limit=10000
2019/05/03 20:35:55 cannot start setup-bridges, interceptor not ready
2019/05/03 20:35:55 cannot start ready-notifier, interceptor not ready
2019/05/03 20:35:55 cannot start search-override, interceptor not ready
2019/05/03 20:35:55 DNS: listening on 127.0.0.1:1233
2019/05/03 20:35:55 cannot start setup-bridges, interceptor not ready
2019/05/03 20:35:55 cannot start ready-notifier, interceptor not ready
2019/05/03 20:35:55 cannot start search-override, interceptor not ready
2019/05/03 20:35:55 pfctl -a teleproxy -F all < 
2019/05/03 20:35:55 No ALTQ support in kernel
ALTQ related functions disabled
rules cleared
nat cleared
dummynet cleared
0 tables deleted.
2019/05/03 20:35:55 pfctl -f /dev/stdin < pass on lo0
2019/05/03 20:35:55 pfctl: Use of -f option, could result in flushing of rules
present in the main ruleset added by the system at startup.
See /etc/pf.conf for further details.

No ALTQ support in kernel
ALTQ related functions disabled
/dev/stdin:1: syntax error
pfctl: Syntax error in config file: pf rules not loaded
2019/05/03 20:35:55 exit status 1
2019/05/03 20:35:55 pfctl -a teleproxy -f /dev/stdin < pass out quick inet proto tcp to 127.0.0.1/32

2019/05/03 20:35:55 pfctl: Use of -f option, could result in flushing of rules
present in the main ruleset added by the system at startup.
See /etc/pf.conf for further details.

No ALTQ support in kernel
ALTQ related functions disabled
2019/05/03 20:35:55 pfctl -a teleproxy -f /dev/stdin < rdr pass on lo0 inet proto udp to 89.101.160.4 -> 127.0.0.1 port 1233
pass out quick inet proto tcp to 127.0.0.1/32
pass out route-to lo0 inet proto udp to 89.101.160.4 keep state

2019/05/03 20:35:55 pfctl: Use of -f option, could result in flushing of rules
present in the main ruleset added by the system at startup.
See /etc/pf.conf for further details.

No ALTQ support in kernel
ALTQ related functions disabled
2019/05/03 20:35:55 pfctl -a teleproxy -f /dev/stdin < rdr pass on lo0 inet proto tcp to 127.254.254.254 -> 127.0.0.1 port 57867
rdr pass on lo0 inet proto udp to 89.101.160.4 -> 127.0.0.1 port 1233
pass out quick inet proto tcp to 127.0.0.1/32
pass out route-to lo0 inet proto tcp to 127.254.254.254 keep state
pass out route-to lo0 inet proto udp to 89.101.160.4 keep state

2019/05/03 20:35:55 pfctl: Use of -f option, could result in flushing of rules
present in the main ruleset added by the system at startup.
See /etc/pf.conf for further details.

No ALTQ support in kernel
ALTQ related functions disabled
2019/05/03 20:35:55 INT: STORE teleproxy.->{teleproxy 127.254.254.254 tcp 57867 }
2019/05/03 20:35:55 starting setup-bridges
2019/05/03 20:35:55 cannot start ready-notifier, search-override not ready
2019/05/03 20:35:55 starting search-override
2019/05/03 20:35:55 DNS: networksetup -listallnetworkservices
2019/05/03 20:35:55 BRG: Setting DNS search path: default.svc.cluster.local.
2019/05/03 20:35:55 cannot start ready-notifier, search-override not ready
2019/05/03 20:35:55 starting teleproxy-pod
2019/05/03 20:35:55 cannot start port-forward, teleproxy-pod not ready
2019/05/03 20:35:55 cannot start ssh-tunnel, port-forward not ready
2019/05/03 20:35:55 starting kubernetes-bridge
2019/05/03 20:35:55 kubernetes-bridge: kubernetes ctx=v1-10 ns=default
2019/05/03 20:35:55 KAP: kubectl --kubeconfig /Users/giovannigargiulo/.kube/config --context v1-10 --namespace default apply -f -
2019/05/03 20:35:55 DNS: An asterisk (*) denotes that a network service is disabled.
2019/05/03 20:35:55 DNS: Wi-Fi
2019/05/03 20:35:55 DNS: networksetup -getsearchdomains Wi-Fi
2019/05/03 20:35:55 DNS: There aren't any Search Domains set on Wi-Fi.
2019/05/03 20:35:55 DNS: networksetup -setsearchdomains Wi-Fi .
2019/05/03 20:35:55 BRG: error setting up search path: Post http://teleproxy/api/search: dial tcp: lookup teleproxy: no such host
2019/05/03 20:35:55 setup-bridges: WORKER PANICKED: Post http://teleproxy/api/search: dial tcp: lookup teleproxy: no such host
goroutine 74 [running]:
runtime/debug.Stack(0xc00010bd48, 0x4e86d20, 0xc0002141b0)
	/usr/local/go/src/runtime/debug/stack.go:24 +0xa7
github.com/datawire/teleproxy/pkg/supervisor.(*Supervisor).launch.func1.1.1(0xc00010bfa8)
	/Users/distiller/repo/pkg/supervisor/supervisor.go:279 +0x60
panic(0x4e86d20, 0xc0002141b0)
	/usr/local/go/src/runtime/panic.go:513 +0x1b9
main.bridges(0xc0001522e0, 0xc00022b300, 0x0, 0x0)
	/Users/distiller/repo/cmd/teleproxy/teleproxy.go:478 +0x4ee
main.main.func2(0xc0001522e0, 0x50681d8, 0xc00015a7a8)
	/Users/distiller/repo/cmd/teleproxy/teleproxy.go:138 +0xcc
github.com/datawire/teleproxy/pkg/supervisor.(*Supervisor).launch.func1.1(0xc00010bfa8, 0xc0000a00c0, 0xc0001522e0)
	/Users/distiller/repo/pkg/supervisor/supervisor.go:283 +0x5e
github.com/datawire/teleproxy/pkg/supervisor.(*Supervisor).launch.func1(0xc0000a00c0, 0xc0001522e0, 0xc00044a000)
	/Users/distiller/repo/pkg/supervisor/supervisor.go:284 +0x4b
created by github.com/datawire/teleproxy/pkg/supervisor.(*Supervisor).launch
	/Users/distiller/repo/pkg/supervisor/supervisor.go:274 +0xb2
2019/05/03 20:35:55 shutting down signal-handler
2019/05/03 20:35:55 cannot shutdown interceptor, search-override still running
2019/05/03 20:35:55 shutting down api-server
2019/05/03 20:35:55 shutting down dns-server
2019/05/03 20:35:55 shutting down proxy-server
2019/05/03 20:35:55 shutting down search-override
2019/05/03 20:35:55 shutting down teleproxy-pod
2019/05/03 20:35:55 shutting down kubernetes-bridge
2019/05/03 20:35:55 cannot shutdown interceptor, search-override still running
2019/05/03 20:35:55 cannot shutdown interceptor, search-override still running
2019/05/03 20:35:55 cannot shutdown interceptor, search-override still running
2019/05/03 20:35:55 cannot shutdown interceptor, search-override still running
2019/05/03 20:35:55 cannot shutdown interceptor, search-override still running
2019/05/03 20:35:55 KAP: signal: killed
2019/05/03 20:35:55 DNS: networksetup -setsearchdomains Wi-Fi There aren't any Search Domains set on Wi-Fi.
2019/05/03 20:35:55 cannot shutdown interceptor, search-override still running
2019/05/03 20:35:56 shutting down interceptor
2019/05/03 20:35:56 Removing rule: anchor teleproxy all
2019/05/03 20:35:56 Removing rule: rdr-anchor teleproxy all
2019/05/03 20:35:56 pfctl -a teleproxy -F all < 
2019/05/03 20:35:56 No ALTQ support in kernel
ALTQ related functions disabled
rules cleared
nat cleared
dummynet cleared
0 tables deleted.
2019/05/03 20:35:56 done
```

**Comment by nemo83** [comment]
Eventually managed to run some tests... the problem seems to be related to the search names in the network configuration. There must be 2 search domain names setup, or it won't work...

**Comment by kflynn** [comment]
Landing this one. I have tests ready to fold in right after...

**Pull request merged**
