### PR TITLE
docs: update Prometheus with Helm location

### PR DESCRIPTION
**Pull request by ellisvalentiner**
Update documentation for Prometheus with Helm location

## Description
Further development has moved to [prometheus-community/helm-charts](https://github.com/prometheus-community/helm-charts).

## Tasks That Must Be Done
- [ ] Did you update CHANGELOG.md?
- [ ] Did you add or update tests?
- [ ] Did you update documentation?
- [ ] Were there any special dev tricks you had to use to work on this code efficiently?
  + [ ] Did you add them to DEVELOPING.md?
- [ ] Is this a build change?
  + [ ] If so, did you test on both Mac and Linux?

## Other
* If this is a documentation change for a particular release, please open the pull request against the release branch.

### CODE REVIEW

**Review by nbkrause — COMMENTED** [review]
@ellisvalentiner Thanks for taking the time to submit this.

One question I have is that the new chart repo has multiple prometheus related charts and does not specifically point to the operator as the old charts repo did. 

Based on [this README](https://github.com/prometheus-operator/prometheus-operator/tree/master/helm) it looks like the operator is now [kube-prometheus-stack](https://github.com/prometheus-community/helm-charts/tree/main/charts/kube-prometheus-stack).

Could you confirm which chart in this repo you are linking to you used to install prometheus and if any of the rest of the install documentation should change to reflect that?

Thanks!

**Comment by kflynn** [comment]
(@ellisvalentiner, are you on our [Slack](https://d6e.co/slack)? That might be a good place to get this wrapped. 🙂 )

**Comment by ellisvalentiner** [comment]
@kflynn I am, sorry been busy with work

**Review by kflynn — APPROVED** [review]
Looks good from here! I'd like @nbkrause to approve too, though. 🙂

**Review by nbkrause — APPROVED** [review]

**Pull request merged**
