### PR TITLE
Adding custom tvars dict filter for webui [apro #881]

### PR DESCRIPTION
**Pull request by alexgervais**
## Description
Customer filter of the diagd json output, specially catered to the `webui` required fields.

## Related Issues
Relates to https://github.com/datawire/apro/issues/881

## Testing
With 200 mappings:
```
~ curl --output /dev/null "http://localhost:8877/ambassador/v0/diag/?json=true"
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 4762k  100 4762k    0     0  1283k      0  0:00:03  0:00:03 --:--:-- 1283k
```
```
~ curl --output /dev/null "http://localhost:8877/ambassador/v0/diag/?json=true&filter=webui"
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 50985  100 50985    0     0   160k      0 --:--:-- --:--:-- --:--:--  160k
```

## Todos
- [x] Tests
- [ ] Documentation

## Other
* If this is a documentation change, please open the pull request at https://github.com/datawire/ambassador-docs instead.
* Code changes should occur against `master`.

### CODE REVIEW

**Comment by ark3** [comment]
This is a great improvement! But I'm concerned it will be difficult to maintain. I'm sure you've tested the Web UI to make sure everything works with these filters _now_, but how do we keep the UI and the filters in sync? Would it be ~possible~ practical to keep the filter specification closer to where the data is consumed?

**Comment by alexgervais** [comment]
@ark3 great valid feedback and concern. I too have a hard time reasoning about the schema-less diag output. I can see value in moving the field selector to `webui` and passing them explicitly in the http request, but I'm not sure it would make future evolutions easier... adding fields to `diag` or consuming extra fields in `webui` means understanding the json representation which is the non-trival task.

**Comment by alexgervais** [comment]
More thoughts on having the frontend pass in the filter query: Since the requested structure has deeply nested elements and filters, I think a good path forward for the webui is to consume this data from a graphql endpoint, rather than a simple "rest" call.
This would mean a structured dataset with a schema and a common filter API.

**Comment by alexgervais** [comment]
@kflynn I'm actually keeping `precedence ` in `route_info`. The listed keys are the ones that are kept:

```
unwanted_keys = set(d) - set(keys_to_keep)
for unwanted_key in unwanted_keys: del d[unwanted_key]
```

**Pull request merged**
