### PR TITLE
Utilizing imageTag in helm deployment

### PR DESCRIPTION
**Pull request by endrec**
The Readme suggests that the `imageTag` parameter can be used to specify the docker image version, but it was not used in the deployment template.

### CODE REVIEW

**Comment by kflynn** [comment]
Looks good (especially in light of #619), thanks! 

My only question: should it be `image.tag`? (If it's easier to work with as `imageTag`, I'm fine with that answer.)

**Comment by endrec** [comment]
Very good question, @kflynn :)
It is not about easiness, it's more about consistency.
It says `imageTag` in the readme, so I thought that should be it. Later I realised the other two is not consistent with the actual template, so I modified the readme, but now the three properties do not follow the same naming convention... :)
I will go with `image.tag`. :)

**Comment by kflynn** [comment]
Thanks!

**Comment by kflynn** [comment]
Pulling this into `shared/develop` for 0.35.3.

**Pull request merged**
